name: Build & Test

on:
  pull_request:
    branches:
      - main



jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: Run docker compose
        run: cd infra && docker compose up -d
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package